// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdzlbwjqltwnenvhfnsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkemxid2pxbHR3bmVudmhmbnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTA3MzEsImV4cCI6MjA3MjA2NjczMX0.pkxRdcZWfkDTWLA6GKzyW_olkN2nUCWJ_6fXe0453d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});